services:
  java-webapp:
    container_name: firmador-java
    build:
      context: ./dssapp
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    networks:
      - signnet

  flask-app:
    container_name: firmador-python-prod
    build:
      context: ./firmar_python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./firmar_python:/app
    depends_on:
      - java-webapp
    networks:
      - signnet

networks:
  signnet:
    driver: bridge