version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - java-webapp
      - flask-app
    networks:
      - signnet

  java-webapp:
    build:
      context: ./dss-demonstrations
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    networks:
      - signnet

  flask-app:
    build:
      context: ./firmar_python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./firmar_python:/app
    depends_on:
      - java-webapp
    network_mode: host

networks:
  signnet:
    driver: bridge
