services:
  flask-app:
    container_name: firmador-python-test
    restart: always
    build:
      context: ./firmar_python
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    volumes:
      - ./firmar_python:/app
      - ../devenv/documentos:/var/documentos
    networks:
      - firmador_firmador_signnet

networks:
  firmador_firmador_signnet:
    external: true