services:
  flask-app:
    container_name: firmador-python
    build:
      context: ./firmar_python
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    volumes:
      - ./firmar_python:/app
    networks:
      - signnet

networks:
  signnet:
    driver: bridge