version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - java-webapp
      - flask-app
    network_mode: host

  java-webapp:
    build:
      context: ./dssapp
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    networks:
      - signnet

  flask-app:
    build:
      context: ./firmar_python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./firmar_python:/app
      - ./certificate.pem:/app/certificate.pem
      - ./private_key.pem:/app/private_key.pem
    depends_on:
      - java-webapp
    networks:
      - signnet

networks:
  signnet:
    driver: bridge
