services:
  flask-app:
    build:
      context: ./firmar_python
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    volumes:
      - ./firmar_python:/app
    depends_on:
      - java-webapp
    networks:
      - signnet

networks:
  signnet:
    driver: bridge
