services:

  java-webapp:
    container_name: firmador-java
    restart: always
    build:
      context: ./dssapp
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    networks:
      - firmador_signnet
  
  flask-app:
    container_name: firmador-python-prod
    restart: always
    build:
      context: ./firmar_python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./firmar_python:/app
    depends_on:
      - java-webapp
    networks:
      - firmador_signnet

networks:
  firmador_signnet:
    driver: bridge