services:
  flask-app:
    container_name: firmador-python-prod
    build:
      context: ./firmar_python
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    volumes:
      - ./firmar_python:/app
    networks:
      - firmador_signnet

networks:
  firmador_signnet:
    external: true