OPERATION_RUNNING = "running"
OPERATION_SUCCESS = "success"
OPERATION_PARTIAL_ERROR = "partial_error"
OPERATION_FAILED = "failed"
OPERATION_REJECTED = "rejected"

SUBJECT_RUNNING = "running"
SUBJECT_SUCCESS = "success"
SUBJECT_WARNING = "warning"
SUBJECT_ERROR = "error"
SUBJECT_SKIPPED = "skipped"

STAGE_RUNNING = "running"
STAGE_SUCCESS = "success"
STAGE_WARNING = "warning"
STAGE_ERROR = "error"
STAGE_SKIPPED = "skipped"

ENTRY_HTTP_REQUEST = "http_request"
ENTRY_HTTP_RESPONSE = "http_response"
ENTRY_EXTERNAL_REQUEST = "external_request"
ENTRY_EXTERNAL_RESPONSE = "external_response"
ENTRY_APP_LOG = "app_log"
ENTRY_ERROR = "error"
